[package]
name = "QUX"
version = "0.1.0"
edition = "2021"
authors = ["Pouya Farahaani <m.p.farahany@gmail.com>"]

[[bin]]
name = "QUX"
path = "src/main.rs"
[dependencies]
getopts = "0.2.21"
image = "0.14"
